services:
  app:
    build: 
      context: .
      args:
        - FILE_TYPE=${FILE_TYPE:-csv}
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - FILE_TYPE=${FILE_TYPE:-csv}
    platform: linux/amd64
    deploy:
      resources:
        limits:
          memory: 64g
          cpus: 10