[destination.filesystem]
bucket_url = "bucket_url" # please set me up!

[destination.filesystem.credentials]
aws_access_key_id = "aws_access_key_id" # please set me up!
aws_secret_access_key = "aws_secret_access_key" # please set me up!
