gateways:
  local:
    connection:
      type: duckdb
      database: db.db
    test_connection:
      type: duckdb
      database: test.db
    state_connection:
      type: duckdb
      database: state.db

default_gateway: local

model_defaults:
  dialect: duckdb
  start: 2025-01-07
