[project]
name = "intro-to-dlt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dlt[duckdb,filesystem,parquet]>=1.10.0",
    "python-dotenv>=1.1.0",
]
