MODEL (
  name lakehouse.base_model,
  kind view,
  cron '@daily',  -- this view gets updated daily at 00:00 UTC
  grain (collision_id),
  description """
    - Base model for the NYC Open Data Motor Vehicle Collisions dataset. 
    - Refer to this documentation for more info: https://data.cityofnewyork.us/Public-Safety/Motor-Vehicle-Collisions-Crashes/h9gi-nx95/about_data
  """,
  column_descriptions (
    collision_id = 'Unique record code generated by system. Primary Key for Crash table.',
    crash_datetime = 'Occurrence datetime of collision',
    crash_time = 'Occurrence time of collision',
    on_street_name = 'Street on which the collision occurred',
    off_street_name = 'Nearest cross street to the collision',
    cross_street_name = 'Street address if known',
    borough = 'Borough where collision occurred',
    zip_code = 'Postal code of incident occurrence',
    latitude = 'Latitude coordinate for Global Coordinate System, WGS 1984, decimal degrees (EPSG 4326) ',
    longitude = 'Longitude coordinate for Global Coordinate System, WGS 1984, decimal degrees (EPSG 4326)',
    -- NOTE: NYC Open Data defines `location` as: "Latitude , Longitude pair".
    -- dlt flattens the nested object into these columns, so these descriptions are derived.
    location = "Latitude , Longitude pair",
    number_of_persons_injured = 'Number of persons injured',
    number_of_persons_killed = 'Number of persons killed',
    number_of_pedestrians_injured = 'Number of pedestrians injured',
    number_of_pedestrians_killed = 'Number of pedestrians killed',
    number_of_cyclist_injured = 'Number of cyclists injured',
    number_of_cyclist_killed = 'Number of cyclists killed',
    number_of_motorist_injured = 'Number of vehicle occupants injured',
    number_of_motorist_killed = 'Number of vehicle occupants killed',
    contributing_factor_vehicle_1 = 'Factors contributing to the collision for designated vehicle',
    contributing_factor_vehicle_2 = 'Factors contributing to the collision for designated vehicle',
    contributing_factor_vehicle_3 = 'Factors contributing to the collision for designated vehicle',
    contributing_factor_vehicle_4 = 'Factors contributing to the collision for designated vehicle',
    contributing_factor_vehicle_5 = 'Factors contributing to the collision for designated vehicle',
    vehicle_type_code1 = 'Type of vehicle based on the selected vehicle category (ATV, bicycle, car/suv, ebike, escooter, truck/bus, motorcycle, other)',
    vehicle_type_code2 = 'Type of vehicle based on the selected vehicle category (ATV, bicycle, car/suv, ebike, escooter, truck/bus, motorcycle, other)',
    vehicle_type_code_3 = 'Type of vehicle based on the selected vehicle category (ATV, bicycle, car/suv, ebike, escooter, truck/bus, motorcycle, other)',
    vehicle_type_code_4 = 'Type of vehicle based on the selected vehicle category (ATV, bicycle, car/suv, ebike, escooter, truck/bus, motorcycle, other)',
    vehicle_type_code_5 = 'Type of vehicle based on the selected vehicle category (ATV, bicycle, car/suv, ebike, escooter, truck/bus, motorcycle, other)',
    _dlt_load_id = 'dlt load identifier (lineage / batch id)',
    _dlt_id = 'dlt unique row identifier'
  ),
  audits (
    unique_values(columns = collision_id),
    not_null(columns = collision_id)
  )
);

SELECT
  -- Primary key / grain
  collision_id::BIGINT,
  -- Event time
  crash_date::TIMESTAMPTZ as crash_datetime,
  crash_time::TIME,
  -- Location (street context)
  on_street_name::TEXT,
  off_street_name::TEXT,
  cross_street_name::TEXT,
  -- Location (geo)
  borough::TEXT,
  zip_code::TEXT,
  latitude::DOUBLE,
  longitude::DOUBLE,
  location::JSON,
  -- Impact counts
  number_of_persons_injured::INTEGER,
  number_of_persons_killed::INTEGER,
  number_of_pedestrians_injured::INTEGER,
  number_of_pedestrians_killed::INTEGER,
  number_of_cyclist_injured::INTEGER,
  number_of_cyclist_killed::INTEGER,
  number_of_motorist_injured::INTEGER,
  number_of_motorist_killed::INTEGER,
  -- Contributing factors
  contributing_factor_vehicle_1::TEXT,
  contributing_factor_vehicle_2::TEXT,
  contributing_factor_vehicle_3::TEXT,
  contributing_factor_vehicle_4::TEXT,
  contributing_factor_vehicle_5::TEXT,
  -- Vehicle type codes
  vehicle_type_code1::TEXT,
  vehicle_type_code2::TEXT,
  vehicle_type_code_3::TEXT,
  vehicle_type_code_4::TEXT,
  vehicle_type_code_5::TEXT,
  -- dlt metadata
  _dlt_load_id::BIGINT,
  _dlt_id::TEXT

FROM nyc_open_data.motor_vehicle_collisions;
