MODEL (
  name lakehouse.incremental_model,
  kind INCREMENTAL_BY_TIME_RANGE (
    time_column crash_date,
    lookback 2  -- look at 2 extra days of data to handle late arriving data
  ),
  cron '@daily',  -- this model runs daily at 00:00 UTC
  grain (collision_id),
  column_descriptions (
    collision_id = 'Unique record code generated by system. Primary Key for Crash table.',
    crash_date = 'Occurrence date of collision',
    crash_time = 'Occurrence time of collision',
    borough = 'Borough where collision occurred',
    zip_code = 'Postal code of incident occurrence',
    number_of_persons_injured = 'Number of persons injured',
    number_of_persons_killed = 'Number of persons killed',
    contributing_factor_vehicle_1 = 'Factors contributing to the collision for designated vehicle',
    vehicle_type_code1 = 'Type of vehicle based on the selected vehicle category (ATV, bicycle, car/suv, ebike, escooter, truck/bus, motorcycle, other)',
    _lakehouse_loaded_at = 'Timestamp of when the record was loaded into the lakehouse',
  ),
  audits (
    unique_values(columns = collision_id),
    not_null(columns = collision_id)
  )
);

SELECT
  -- Primary key / grain
  collision_id,
  -- Time
  crash_date,
  crash_time,
  -- Location
  borough,
  zip_code,
  -- Impact counts
  number_of_persons_injured,
  number_of_persons_killed,
  -- contributing factors
  contributing_factor_vehicle_1, 
  -- Vehicle information
  vehicle_type_code1,
  -- lakehouse metadata
  CURRENT_TIMESTAMP() AS _lakehouse_loaded_at,

FROM lakehouse.base_model
WHERE crash_date BETWEEN @start_date AND @end_date;
